project:
  type: website
  output-dir: docs

website:
  title: "Data-Driven Statistics with AI"
  navbar:
    title: ""
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About this course
      - href: schedule.qmd
        text: Course schedule
      - href: course_project.qmd
        text: Course project
      - href: faqs.qmd
        text: FAQs
    tools:
      - icon: github
        menu: 
          - text: Source Code
            href: 
          - text: Report a Bug
            href: 

format:
  html:
    theme: cosmo
    respect-user-color-scheme: true
    css: styles.css
    toc: true
    smooth-scroll: true 

editor: visual

